# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Ui_Pencere(object):
    def setupUi(self, Pencere):
        Pencere.setObjectName("Pencere")
        Pencere.resize(350, 250)
        Pencere.setMinimumSize(QtCore.QSize(350, 250))
        Pencere.setMaximumSize(QtCore.QSize(350, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Pencere.setWindowIcon(icon)
        Pencere.setStyleSheet("QWidget {\n"
"    background-color:rgb(0, 0, 0);\n"
"    color: rgb(240, 240, 240);\n"
"    border-color: rgb(58, 58, 58);\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    background-color:rgb(0, 0, 0);\n"
"    color: rgb(200, 200, 200);\n"
"    selection-background-color: rgb(255, 153, 0);\n"
"    selection-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"        border-top: 1px solid #000000;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"     background-color:rgb(0, 0, 0);\n"
"     border-style: outset;\n"
"    border-width: 1px;\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"  border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-top-width: 0px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 153, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"   color: rgb(255, 255, 255);\n"
"   background-color:rgb(0, 0, 0);\n"
"   border-color:rgb(42, 42, 42);\n"
"   margin-left: 0px;\n"
"   margin-right: 0px;\n"
"   border-bottom-right-radius:4px;\n"
"   border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QTabBar::tab:last:selected {\n"
"  background-color:rgb(0, 0, 0);\n"
"    border-color:rgb(42, 42, 42);\n"
"    margin-left: 0px;\n"
"      margin-right: 0px;\n"
"    border-bottom-right-radius:4px;\n"
"    border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"   margin-bottom: 4px;\n"
"   border-bottom-right-radius:4px;\n"
"   border-bottom-left-radius:4px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(0, 0, 0);\n"
"    padding: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(57, 57, 57, 255), stop:1 rgba(77, 77, 77, 255));\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(101, 101, 101);\n"
"    selection-background-color: rgb(187, 187, 187);\n"
"    selection-color: rgb(60, 63, 65);\n"
"}\n"
"\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(255, 255, 255);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(0, 200, 0, 255), stop:1 rgba(30, 230, 30, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background:rgb(0, 0, 0);\n"
"    color: rgb(255, 153, 0);\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"      spacing: 3px; \n"
"    padding: 1px 4px;\n"
"      background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected { \n"
"      background:rgb(115, 115, 115);\n"
"}\n"
"\n"
"QMenu {\n"
"    border-width: 2px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(255, 153, 0);\n"
"    border-style: outset;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    spacing: 3px; \n"
"    padding: 3px 15px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    spacing: 3px; \n"
"    padding: 3px 15px;\n"
"    background:rgb(115, 115, 115);\n"
"    color:rgb(255, 255, 255);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"}")
        Pencere.setDockNestingEnabled(False)
        self.fatura = QtWidgets.QWidget(Pencere)
        self.fatura.setObjectName("fatura")
        self.btn_hesapla = QtWidgets.QPushButton(self.fatura)
        self.btn_hesapla.setGeometry(QtCore.QRect(260, 10, 71, 41))
        self.btn_hesapla.setObjectName("btn_hesapla")
        self.btn_yazdir = QtWidgets.QPushButton(self.fatura)
        self.btn_yazdir.setGeometry(QtCore.QRect(260, 70, 71, 41))
        self.btn_yazdir.setObjectName("btn_yazdir")
        self.ln_litre = QtWidgets.QLineEdit(self.fatura)
        self.ln_litre.setGeometry(QtCore.QRect(110, 50, 113, 20))
        self.ln_litre.setObjectName("ln_litre")
        self.ln_plaka = QtWidgets.QLineEdit(self.fatura)
        self.ln_plaka.setGeometry(QtCore.QRect(110, 90, 111, 21))
        self.ln_plaka.setClearButtonEnabled(True)
        self.ln_plaka.setObjectName("ln_plaka")
        self.lbl_litre = QtWidgets.QLabel(self.fatura)
        self.lbl_litre.setGeometry(QtCore.QRect(30, 50, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_litre.setFont(font)
        self.lbl_litre.setObjectName("lbl_litre")
        self.lbl_plaka = QtWidgets.QLabel(self.fatura)
        self.lbl_plaka.setGeometry(QtCore.QRect(30, 90, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_plaka.setFont(font)
        self.lbl_plaka.setObjectName("lbl_plaka")
        self.lbl_fiyat = QtWidgets.QLabel(self.fatura)
        self.lbl_fiyat.setGeometry(QtCore.QRect(30, 10, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fiyat.setFont(font)
        self.lbl_fiyat.setObjectName("lbl_fiyat")
        self.ln_fiyat = QtWidgets.QLineEdit(self.fatura)
        self.ln_fiyat.setGeometry(QtCore.QRect(110, 10, 113, 20))
        self.ln_fiyat.setText("")
        self.ln_fiyat.setObjectName("ln_fiyat")
        self.lbl_cikti = QtWidgets.QLabel(self.fatura)
        self.lbl_cikti.setGeometry(QtCore.QRect(20, 160, 221, 71))
        self.lbl_cikti.setText("")
        self.lbl_cikti.setObjectName("lbl_cikti")
        self.btn_temizle = QtWidgets.QPushButton(self.fatura)
        self.btn_temizle.setGeometry(QtCore.QRect(260, 130, 71, 41))
        self.btn_temizle.setObjectName("btn_temizle")
        self.ln_pno = QtWidgets.QLineEdit(self.fatura)
        self.ln_pno.setGeometry(QtCore.QRect(110, 130, 111, 21))
        self.ln_pno.setClearButtonEnabled(False)
        self.ln_pno.setObjectName("ln_pno")
        self.lbl_pno = QtWidgets.QLabel(self.fatura)
        self.lbl_pno.setGeometry(QtCore.QRect(20, 130, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pno.setFont(font)
        self.lbl_pno.setObjectName("lbl_pno")
        Pencere.setCentralWidget(self.fatura)
        self.statusbar = QtWidgets.QStatusBar(Pencere)
        self.statusbar.setObjectName("statusbar")
        Pencere.setStatusBar(self.statusbar)

        self.retranslateUi(Pencere)
        QtCore.QMetaObject.connectSlotsByName(Pencere)

    def retranslateUi(self, Pencere):
        _translate = QtCore.QCoreApplication.translate
        Pencere.setWindowTitle(_translate("Pencere", "Fiş Uygulaması"))
        self.btn_hesapla.setText(_translate("Pencere", "HESAPLA"))
        self.btn_yazdir.setText(_translate("Pencere", "YAZDIR"))
        self.lbl_litre.setText(_translate("Pencere", "Litre:"))
        self.lbl_plaka.setText(_translate("Pencere", "Plaka:"))
        self.lbl_fiyat.setText(_translate("Pencere", "Fiyat:"))
        self.btn_temizle.setText(_translate("Pencere", "TEMİZLE"))
        self.lbl_pno.setText(_translate("Pencere", "Pompa No:"))

class Errors(QMainWindow):
    def __init__(self):
        super().__init__()
        self.widget = QWidget(self)
        self.setCentralWidget(self.widget)
    def hesapla_error(self):
        QMessageBox.critical(self, "UYARI", "Hatalı içerik girişinde bulundunuz. Lütfen Tekrar Deneyiniz!")
    def yazdir_error(self):
        QMessageBox.critical(self, "UYARI", "Yazdırılırken hata ile karşılaşıldı. Lütfen Yazıcınızı ve Yazıcı Ayarlarını Kontrol Ediniz!!")

